name: 'build'

permissions: {}
on:
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup NodeJS
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install

      - name: Install TypeScript
        run: |
          npm install -g typescript

      - name: Build packages
        run: |
          npm --workspaces run build

      - name: Pack packages
        run: |
          npm --workspaces pack

      - name: Rename artifacts
        run: |
          export CLIENT_VERSION=$(cat package.json | jq -r '.version')
          mv clickhouse-client-${CLIENT_VERSION}.tgz clickhouse-client.tgz
          mv clickhouse-client-common-${CLIENT_VERSION}.tgz clickhouse-client-common.tgz
          mv clickhouse-client-web-${CLIENT_VERSION}.tgz clickhouse-client-web.tgz

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: clickhouse-js-packages
          path: clickhouse-client*.tgz
