name: 'build'

permissions: {}
on:
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install

      - name: Install TypeScript
        run: |
          npm install -g typescript

      - name: Build Common package
        run: |
          npx tsx .build/build_and_prepare.ts common && npm pack

      - name: Build Node.js package
        run: |
          npx tsx .build/build_and_prepare.ts node && npm pack
      - name: Build Web package
        run: |
          npx tsx .build/build_and_prepare.ts web && npm pack

      - name: Rename artifacts
        run: |
          export CLIENT_VERSION=$(cat package.json | jq -r '.version')
          mv clickhouse-client-${CLIENT_VERSION}.tgz clickhouse-client.tgz
          mv clickhouse-client-common-${CLIENT_VERSION}.tgz clickhouse-client-common.tgz
          mv clickhouse-client-web-${CLIENT_VERSION}.tgz clickhouse-client-web.tgz

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: clickhouse-js-packages
          path: clickhouse-client*.tgz
