name: 'build'

permissions: {}
on: [push]

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup NodeJS
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install

      - name: Build packages
        run: |
          npm --workspaces run build

      - name: Pack packages
        run: |
          npm --workspaces pack

      - name: Rename artifacts
        run: |
          mkdir -p packs
          mv clickhouse-client-common-*.tgz packs/clickhouse-client-common.tgz
          mv clickhouse-client-web-*.tgz packs/clickhouse-client-web.tgz
          mv clickhouse-client-*.tgz packs/clickhouse-client.tgz

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: clickhouse-js-packages
          path: packs/*
