name: 'npm'

permissions: {}
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  test-install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install and run the latest package version
        run: |
          mkdir e2e-test
          cd e2e-test
          npm init -y
          npm install @clickhouse/client
          cat package.json
          node <<EOF
          const { createClient } = require('@clickhouse/client');
          console.log(createClient({ url: 'http://localhost:8123' }));
          EOF
